In [1]:
fd = [
    {
    "name" : "박태원",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01091603776"  
    },
    {
    "name" : "정지영",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01071228966"
    },
    {
    "name" : "김정표",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01041219495"
    },
    {
    "name" : "임예찬",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01041380593"
    },
    {
    "name" : "김한빈",
    "age" : 26,
    "area" : "Seoul",
    "Phone" : "01099172895"
    },
    {
    "name" : "류성열",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01092834152"
    },
    {
    "name" : "김현하",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01051130589"
    },
    {
    "name" : "장준호",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01029499476"
    },
    {"name" : "김찬우",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01050221997"
    },
    {
    "name" : "송상훈",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01097643553"
    },
    {
    "name" : "김진무",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01041518906"
    },
    {
    "name" : "김주용",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01064662850"
    },
    {
    "name" : "김치완",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01099406132"
    },
    {
    "name" : "홍준기",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01037409711"
    },
    {
    "name" : "한상표",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01050923892"
    },
    {
    "name" : "정종영",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01093708185"
    },
    {
    "name" : "이준희",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01052738174"
    },
    {
    "name" : "박상수",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01064354781"
    },
    {
    "name" : "전채환",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01052053975"
    },
    {
    "name" : "박소정",
    "age" : 27,
    "area" : "Seoul",
    "Phone" : "01096960754"
    }

]

In [2]:
_list = []
for i in fd:
    _list.append(i)

print(_list)

[{'name': '박태원', 'age': 27, 'area': 'Seoul', 'Phone': '01091603776'}, {'name': '정지영', 'age': 27, 'area': 'Seoul', 'Phone': '01071228966'}, {'name': '김정표', 'age': 27, 'area': 'Seoul', 'Phone': '01041219495'}, {'name': '임예찬', 'age': 27, 'area': 'Seoul', 'Phone': '01041380593'}, {'name': '김한빈', 'age': 26, 'area': 'Seoul', 'Phone': '01099172895'}, {'name': '류성열', 'age': 27, 'area': 'Seoul', 'Phone': '01092834152'}, {'name': '김현하', 'age': 27, 'area': 'Seoul', 'Phone': '01051130589'}, {'name': '장준호', 'age': 27, 'area': 'Seoul', 'Phone': '01029499476'}, {'name': '김찬우', 'age': 27, 'area': 'Seoul', 'Phone': '01050221997'}, {'name': '송상훈', 'age': 27, 'area': 'Seoul', 'Phone': '01097643553'}, {'name': '김진무', 'age': 27, 'area': 'Seoul', 'Phone': '01041518906'}, {'name': '김주용', 'age': 27, 'area': 'Seoul', 'Phone': '01064662850'}, {'name': '김치완', 'age': 27, 'area': 'Seoul', 'Phone': '01099406132'}, {'name': '홍준기', 'age': 27, 'area': 'Seoul', 'Phone': '01037409711'}, {'name': '한상표', 'age': 27, 'area': 'Seoul', 'Phone': '01050923892'}, {'name': '정종영', 'age': 27, 'area': 'Seoul', 'Phone': '01093708185'}, {'name': '이준희', 'age': 27, 'area': 'Seoul', 'Phone': '01052738174'}, {'name': '박상수', 'age': 27, 'area': 'Seoul', 'Phone': '01064354781'}, {'name': '전채환', 'age': 27, 'area': 'Seoul', 'Phone': '01052053975'}, {'name': '박소정', 'age': 27, 'area': 'Seoul', 'Phone': '01096960754'}]